package com.security.jwt.controller;

import com.security.jwt.model.User;
import com.security.jwt.model.UserRequest;
import com.security.jwt.model.UserResponse;
import com.security.jwt.service.IUserService;
import com.security.jwt.util.JwtUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.security.Principal;

@RestController
@RequestMapping("/user")
public class UserRestController {

    @Autowired
    private IUserService userService; //HAS-A

    @Autowired
    private JwtUtil jwtUtil; //HAS-A

    @Autowired
    private AuthenticationManager authenticationManager;

//    1. save user data in db
    @PostMapping("/save")
    public ResponseEntity<String> saveUser(@RequestBody User user){
        Integer id = userService.saveUser(user);
        String body = "User with id: '"+id+"' saved";
        return  ResponseEntity.ok(body);
    }

    //2. Validate user and generate token(login)
    @PostMapping("/login")
    public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest){
//        validate username/password with db
        authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(userRequest.getUsername(), userRequest.getPassword()));
        String token = jwtUtil.generateToken(userRequest.getUsername());
        return ResponseEntity.ok(new UserResponse(token, "Success! token generated by Honnu"));
    }

    //3. After login, access this
    @PostMapping("/welcome")
    public ResponseEntity<String> accessData(Principal p){
        return ResponseEntity.ok("Hello User "+p.getName());
    }

}
